name: Code Quality & Testing

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Check formatting (Linting)
        run: dotnet format --verify-no-changes --severity warn

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --configuration Release --verbosity normal --filter "FullyQualifiedName!~Integration"
